### PR TITLE
KGLOBAL-4376: Regenerate sdk with some cluster linking changes

### PR DESCRIPTION
**Pull request by andymg3**
Ran `make gen-deps`

### CODE REVIEW

**Review by linouk23 — APPROVED** [review]

**Comment by linouk23** [comment]
@andymg3 did you run `go vet -v` to ensure the package compiles successfully?

**Review by chernyih — COMMENTED** [review]
Should we only pull in relevant changes for cluster linking?

**Comment by andymg3** [comment]
> Should we only pull in relevant changes for cluster linking?

Yeah I think I agree. Updated to pull in some cluster linking changes.

**Review by chernyih — APPROVED** [review]
lgtm

**Comment by andymg3** [comment]
@linouk23 `go vet -v` ran successfully with the most recent update

**Pull request merged**
